apiVersion: v1
entries:
  mayastor:
  - apiVersion: v2
    created: "2022-03-14T19:46:00.35102833+02:00"
    dependencies:
    - condition: etcd.enabled
      name: etcd
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-etcd
      version: 6.2.3
    description: Mayastor Helm chart for Kubernetes
    digest: 8a036f1ee5639b43c7d322b20332ac0b905455001ec2e78b3502cb6b90f34398
    name: mayastor
    type: application
    urls:
    - mayastor-0.0.1.tgz
    version: 0.0.1
generated: "2022-03-14T19:46:00.346741163+02:00"
